version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./src/php:/var/www/html/src/php
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    depends_on:
      - node

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - ./src/react:/app/src
      - ./public/assets/js/bundle:/app/public/assets/js/bundle
      - ./package.json:/app/package.json
      - ./webpack.config.js:/app/webpack.config.js
      - node_modules:/app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development

volumes:
  node_modules: